version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - curl -fsSL https://raw.githubusercontent.com/fishbrain/aws-codebuild-extras/master/install -o /tmp/aws-install && . /tmp/aws-install
  build:
    on-failure: ABORT
    commands:
      - echo "🏗️ Building engineering-blog..."
      - yarn && yarn build && yarn export
  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ] && [ "$CODEBUILD_GIT_BRANCH" = main ]; then
          echo "Deploying ${FISHBRAIN_ENVIRONMENT} from branch ${CODEBUILD_GIT_BRANCH}"
          echo "... uploading to ${S3_OUTPUT_URL}"
          aws s3 sync out ${S3_OUTPUT_URL} --delete
          echo "... done"
        fi
