name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://engineering.fishbrain.com

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Install
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Deploy
        if: ${{ success() }}
        run: |
          echo "Deploying production to ${{ secrets.S3_OUTPUT_URL }} from Github environment"
          echo "... uploading to ${{ secrets.S3_OUTPUT_URL }}"
          aws s3 sync _site ${{ secrets.S3_OUTPUT_URL }} --delete
          echo "... done"
