name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://engineering.fishbrain.com

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Install
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Deploy
        if: ${{ success() }}
        run: |
          echo "Deploying production to ${{ secrets.S3_OUTPUT_URL }} from Github environment"
          echo "... uploading to ${{ secrets.S3_OUTPUT_URL }}"
          aws s3 sync _site ${{ secrets.S3_OUTPUT_URL }} --delete
          echo "... done"
